### ISSUE TITLE
com.ibm.diagnostics.healthcenter.plugins WARNING: [cpu_os] At least one data gathering failure occurred

### ISSUE THREAD

**Issue by majgis** [RuntimeTools/appmetrics#258]
I see the following error when starting appmetrics in a production environment:

```
[Thu Jul 14 15:25:16 2016] com.ibm.diagnostics.healthcenter.plugins WARNING: [cpu_os] At least one data gathering failure occurred
```

I don't see the issue when I'm testing.  I'm guessing it might be a permission issue, where can I find more details on how to fix?

**Comment by tobespc** [comment]
@majgis have you installed appmetrics from the git repo or from npmjs ?

**Comment by majgis** [comment]
I installed from npmjs.

**Comment by majgis** [comment]
Can someone point me to the line in this code where it makes the system call for cpu and memory?

**Comment by stalleyj** [comment]
Cpu and memory information come from our common plugins in omr-agentcore. You'll find the code for each of them under here omr-agentcore/src/ibmras/monitoring/plugins/common/

**Comment by majgis** [comment]
I tracked down the call for CPU to perfstat_cpu_total in libperfstat:
https://github.com/RuntimeTools/omr-agentcore/blob/master/src/ibmras/monitoring/plugins/common/cpu/cpuplugin.cpp#L318

I'm still trying to track down the source for libperfstat...

**Comment by majgis** [comment]
Looks like it is permissions around /proc/stat:
https://github.com/RuntimeTools/omr-agentcore/blob/master/src/ibmras/monitoring/plugins/common/cpu/cpuplugin.cpp#L434

and /proc/<pid>/stat:
https://github.com/RuntimeTools/omr-agentcore/blob/master/src/ibmras/monitoring/plugins/common/memory/MemoryPlugin.cpp#L403

I'm doing work to confirm...

**Comment by majgis** [comment]
I was wrong.  I set the log level to debug.  It looks like an issue with parsing the data.  It is on Centos 6.8.

```
-sh-4.1$ cat test-pm.log 
[ 2016-08-12 16:24:07.2008 4765/7f2123cd7800 age/Wat/WatchdogMain.cpp:1291 ]: Starting Passenger watchdog...
[ 2016-08-12 16:24:07.2152 4768/7f6e72c88800 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2016-08-12 16:24:07.2154 4768/7f6e72c88800 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2016-08-12 16:24:07.2188 4768/7f6e72c88800 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 4768
[ 2016-08-12 16:24:07.2262 4773/7f85ad985800 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2016-08-12 16:24:07.2270 4773/7f85ad985800 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 4773
App 4799 stdout: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 1.0.12.201606140822 (Agent Core 3.0.9)
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libmemoryplugin.so, version 1.0
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libenvplugin.so, version 1.0
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libnodeenvplugin.so, version 1.0
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libcpuplugin.so, version 1.0
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libhcapiplugin.so, version 1.0
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libnodeprofplugin.so, version 3.0
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libhcmqtt.so, version 1.0
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libnodegcplugin.so, version 1.0
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.Agent FINE: System receiver, version 1.0
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [memory_os] Registering pull source
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [memory_os] Registering pull source
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins FINE: >>>ibmras_monitoring_registerPullSource
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [env_os] Registering pull source
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins FINE: <<<ibmras_monitoring_registerPullSource
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [environment_node] Registering push sources
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins FINE: >>>ibmras_monitoring_registerPullSource
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [cpu_os] Registering pull source
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins FINE: CpuPlugin::createPullSource
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins FINE: <<<ibmras_monitoring_registerPullSource
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [api_push] Registering push sources
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [profiling_node] Registering push sources
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [gc_node] Registering push sources
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [memory_os] Starting
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [environment_os] Starting
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>EnvPlugin::start()
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<EnvPlugin::start()
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [environment_node] Starting
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::start()
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::start()
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [profiling_node] Starting disabled
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [profiling_node] Publishing config
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [profiling_node] Sending config message [profiling_node_subsystem=off]
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:07 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [gc_node] Starting
App 4799 stderr: 
App 4831 stdout: 
App 4799 stderr: [Fri Aug 12 16:24:08 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>EnvPlugin::OnRequestData
App 4799 stderr: [Fri Aug 12 16:24:08 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<EnvPlugin::OnRequestData
App 4799 stderr: [Fri Aug 12 16:24:08 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::OnRequestData
App 4799 stderr: [Fri Aug 12 16:24:08 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::getCPUTime
App 4799 stderr: [Fri Aug 12 16:24:08 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_total_cpu_time
App 4799 stderr: [Fri Aug 12 16:24:08 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_process_cpu_time
App 4799 stderr: [Fri Aug 12 16:24:08 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Failed to parse /proc/4799/stat
App 4799 stderr: [Fri Aug 12 16:24:08 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:08 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:08 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:08 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:08 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Skipped sending data (reason: invalid data)
App 4799 stderr: [Fri Aug 12 16:24:08 2016] com.ibm.diagnostics.healthcenter.plugins WARNING: [cpu_os] At least one data gathering failure occurred
App 4799 stderr: [Fri Aug 12 16:24:08 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::OnRequestData
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 1.0.12.201606140822 (Agent Core 3.0.9)
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libmemoryplugin.so, version 1.0
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libenvplugin.so, version 1.0
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libnodeenvplugin.so, version 1.0
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libcpuplugin.so, version 1.0
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libhcapiplugin.so, version 1.0
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libnodeprofplugin.so, version 3.0
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libhcmqtt.so, version 1.0
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.Plugin FINE: /opt/test/node_modules/test/node_modules/test-monitor/node_modules/appmetrics/plugins/libnodegcplugin.so, version 1.0
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.Agent FINE: System receiver, version 1.0
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [memory_os] Registering pull source
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [memory_os] Registering pull source
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins FINE: >>>ibmras_monitoring_registerPullSource
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [env_os] Registering pull source
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins FINE: <<<ibmras_monitoring_registerPullSource
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [environment_node] Registering push sources
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins FINE: >>>ibmras_monitoring_registerPullSource
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [cpu_os] Registering pull source
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins FINE: CpuPlugin::createPullSource
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins FINE: <<<ibmras_monitoring_registerPullSource
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [api_push] Registering push sources
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [profiling_node] Registering push sources
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [gc_node] Registering push sources
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [memory_os] Starting
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [environment_os] Starting
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>EnvPlugin::start()
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<EnvPlugin::start()
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [environment_node] Starting
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::start()
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::start()
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [profiling_node] Starting disabled
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [profiling_node] Publishing config
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [profiling_node] Sending config message [profiling_node_subsystem=off]
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:09 2016] com.ibm.diagnostics.healthcenter.plugins FINE: [gc_node] Starting
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:10 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>EnvPlugin::OnRequestData
App 4831 stderr: [Fri Aug 12 16:24:10 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<EnvPlugin::OnRequestData
App 4831 stderr: [Fri Aug 12 16:24:10 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::OnRequestData
App 4831 stderr: [Fri Aug 12 16:24:10 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::getCPUTime
App 4831 stderr: [Fri Aug 12 16:24:10 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_total_cpu_time
App 4831 stderr: [Fri Aug 12 16:24:10 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_process_cpu_time
App 4831 stderr: [Fri Aug 12 16:24:10 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Failed to parse /proc/4831/stat
App 4831 stderr: [Fri Aug 12 16:24:10 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:10 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:10 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:10 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:10 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Skipped sending data (reason: invalid data)
App 4831 stderr: [Fri Aug 12 16:24:10 2016] com.ibm.diagnostics.healthcenter.plugins WARNING: [cpu_os] At least one data gathering failure occurred
App 4831 stderr: [Fri Aug 12 16:24:10 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::OnRequestData
App 4799 stderr: [Fri Aug 12 16:24:11 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::OnRequestData
App 4799 stderr: [Fri Aug 12 16:24:11 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::getCPUTime
App 4799 stderr: [Fri Aug 12 16:24:11 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_total_cpu_time
App 4799 stderr: [Fri Aug 12 16:24:11 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_process_cpu_time
App 4799 stderr: [Fri Aug 12 16:24:11 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Failed to parse /proc/4799/stat
App 4799 stderr: [Fri Aug 12 16:24:11 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:11 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:11 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:11 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:11 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Skipped sending data (reason: invalid data)
App 4799 stderr: [Fri Aug 12 16:24:11 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::OnRequestData
App 4831 stderr: [Fri Aug 12 16:24:13 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::OnRequestData
App 4831 stderr: [Fri Aug 12 16:24:13 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::getCPUTime
App 4831 stderr: [Fri Aug 12 16:24:13 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_total_cpu_time
App 4831 stderr: [Fri Aug 12 16:24:13 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_process_cpu_time
App 4831 stderr: [Fri Aug 12 16:24:13 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Failed to parse /proc/4831/stat
App 4831 stderr: [Fri Aug 12 16:24:13 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:13 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:13 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:13 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:13 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Skipped sending data (reason: invalid data)
App 4831 stderr: [Fri Aug 12 16:24:13 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::OnRequestData
App 4799 stderr: [Fri Aug 12 16:24:14 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::OnRequestData
App 4799 stderr: [Fri Aug 12 16:24:14 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::getCPUTime
App 4799 stderr: [Fri Aug 12 16:24:14 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_total_cpu_time
App 4799 stderr: [Fri Aug 12 16:24:14 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_process_cpu_time
App 4799 stderr: [Fri Aug 12 16:24:14 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Failed to parse /proc/4799/stat
App 4799 stderr: [Fri Aug 12 16:24:14 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:14 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:14 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:14 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:14 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Skipped sending data (reason: invalid data)
App 4799 stderr: [Fri Aug 12 16:24:14 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::OnRequestData
App 4831 stderr: [Fri Aug 12 16:24:16 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::OnRequestData
App 4831 stderr: [Fri Aug 12 16:24:16 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::getCPUTime
App 4831 stderr: [Fri Aug 12 16:24:16 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_total_cpu_time
App 4831 stderr: [Fri Aug 12 16:24:16 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_process_cpu_time
App 4831 stderr: [Fri Aug 12 16:24:16 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Failed to parse /proc/4831/stat
App 4831 stderr: [Fri Aug 12 16:24:16 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:16 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:16 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:16 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:16 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Skipped sending data (reason: invalid data)
App 4831 stderr: [Fri Aug 12 16:24:16 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::OnRequestData
App 4799 stderr: [Fri Aug 12 16:24:17 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::OnRequestData
App 4799 stderr: [Fri Aug 12 16:24:17 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::getCPUTime
App 4799 stderr: [Fri Aug 12 16:24:17 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_total_cpu_time
App 4799 stderr: [Fri Aug 12 16:24:17 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_process_cpu_time
App 4799 stderr: [Fri Aug 12 16:24:17 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Failed to parse /proc/4799/stat
App 4799 stderr: [Fri Aug 12 16:24:17 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:17 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:17 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:17 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:17 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Skipped sending data (reason: invalid data)
App 4799 stderr: [Fri Aug 12 16:24:17 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::OnRequestData
App 4831 stderr: [Fri Aug 12 16:24:19 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::OnRequestData
App 4831 stderr: [Fri Aug 12 16:24:19 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::getCPUTime
App 4831 stderr: [Fri Aug 12 16:24:19 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_total_cpu_time
App 4831 stderr: [Fri Aug 12 16:24:19 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_process_cpu_time
App 4831 stderr: [Fri Aug 12 16:24:19 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Failed to parse /proc/4831/stat
App 4831 stderr: [Fri Aug 12 16:24:19 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:19 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:19 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:19 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:19 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Skipped sending data (reason: invalid data)
App 4831 stderr: [Fri Aug 12 16:24:19 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::OnRequestData
App 4799 stderr: [Fri Aug 12 16:24:20 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::OnRequestData
App 4799 stderr: [Fri Aug 12 16:24:20 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::getCPUTime
App 4799 stderr: [Fri Aug 12 16:24:20 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_total_cpu_time
App 4799 stderr: [Fri Aug 12 16:24:20 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_process_cpu_time
App 4799 stderr: [Fri Aug 12 16:24:20 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Failed to parse /proc/4799/stat
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:20 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:20 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:20 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:20 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:20 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Skipped sending data (reason: invalid data)
App 4799 stderr: [Fri Aug 12 16:24:20 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::OnRequestData
App 4831 stderr: [Fri Aug 12 16:24:22 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::OnRequestData
App 4831 stderr: [Fri Aug 12 16:24:22 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::getCPUTime
App 4831 stderr: [Fri Aug 12 16:24:22 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_total_cpu_time
App 4831 stderr: [Fri Aug 12 16:24:22 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_process_cpu_time
App 4831 stderr: [Fri Aug 12 16:24:22 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Failed to parse /proc/4831/stat
App 4831 stderr: [Fri Aug 12 16:24:22 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:22 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:22 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:22 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:22 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Skipped sending data (reason: invalid data)
App 4831 stderr: [Fri Aug 12 16:24:22 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::OnRequestData
App 4799 stderr: [Fri Aug 12 16:24:23 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::OnRequestData
App 4799 stderr: 
App 4799 stderr: [Fri Aug 12 16:24:23 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::getCPUTime
App 4799 stderr: [Fri Aug 12 16:24:23 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_total_cpu_time
App 4799 stderr: [Fri Aug 12 16:24:23 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_process_cpu_time
App 4799 stderr: [Fri Aug 12 16:24:23 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Failed to parse /proc/4799/stat
App 4799 stderr: [Fri Aug 12 16:24:23 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:23 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:23 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:23 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4799 stderr: [Fri Aug 12 16:24:23 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Skipped sending data (reason: invalid data)
App 4799 stderr: [Fri Aug 12 16:24:23 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::OnRequestData
App 4831 stderr: [Fri Aug 12 16:24:25 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::OnRequestData
App 4831 stderr: [Fri Aug 12 16:24:25 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::getCPUTime
App 4831 stderr: [Fri Aug 12 16:24:25 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_total_cpu_time
App 4831 stderr: [Fri Aug 12 16:24:25 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>read_process_cpu_time
App 4831 stderr: [Fri Aug 12 16:24:25 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Failed to parse /proc/4831/stat
App 4831 stderr: [Fri Aug 12 16:24:25 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4831 stderr: 
App 4831 stderr: [Fri Aug 12 16:24:25 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:25 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: >>>CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:25 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::IsValidData
App 4831 stderr: [Fri Aug 12 16:24:25 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: [cpu_os] Skipped sending data (reason: invalid data)
App 4831 stderr: [Fri Aug 12 16:24:25 2016] com.ibm.diagnostics.healthcenter.plugins DEBUG: <<<CpuPlugin::OnRequestData
```

**Comment by majgis** [comment]
I confirmed that it is not a permission issue.  The error is associated with parsing the data.

**Comment by majgis** [comment]
Fronted with Phusion Passenger:
```
$ cat /proc/14077/stat
14077 (Passenger NodeA) S 14042 14042 14039 0 -1 4202496 18057 504 101 0 140 31 0 0 20 0 9 0 7242674 995299328 19374 18446744073709551615 1 1 0 0 0 0 0 4096 16898 18446744073709551615 0 0 17 0 0 0 163 0 0
```
Started normally:
```
$ cat /proc/14248/stat
14248 (node) S 14226 14248 13993 34816 14258 4202496 15838 0 0 0 111 10 0 0 20 0 9 0 7297154 993169408 18237 18446744073709551615 4194304 23407304 140727082367616 140727082354296 140554763756297 0 0 4096 134234626 18446744073709551615 0 0 17 0 0 0 0 0 0```

I'm guessing that the unanticipated space in `(Passenger NodeA)` is causing the issue.

**Comment by majgis** [comment]
It looks like this is the line parsing these values from the file:
https://github.com/RuntimeTools/omr-agentcore/blob/master/src/ibmras/monitoring/plugins/common/cpu/cpuplugin.cpp#L442

**Comment by majgis** [comment]
Looks like the issue is on this line:
https://github.com/RuntimeTools/omr-agentcore/blob/caf73931204bba16a0383768a50d4573f2fa99a9/src/ibmras/monitoring/plugins/common/cpu/cpuplugin.cpp#L561

**Comment by majgis** [comment]
I tested the libcpuplugin.so file compiled from @baens pull-request, and it fixed the issue, no errors were logged.

**Comment by tobespc** [comment]
closing as error is fixed

**Comment by mattcolegate** [comment]
@gustavomassa can you have a look at https://www.ibm.com/support/knowledgecenter/en/SS3KLZ/com.ibm.java.diagnostics.healthcenter.doc/topics/ts_nocpudata.html and see if what's there resolves the issue please?

**Comment by gustavomassa** [comment]
@mattcolegate sure, I have done the commands, PerfOS was already enabled, I rebuilded the counters using the command lodctr /r , but still facing the same issue.

**Comment by mattcolegate** [comment]
@gustavomassa do you get any CPU data through at all?

**Comment by gustavomassa** [comment]
@mattcolegate no CPU data at all.
![image](https://user-images.githubusercontent.com/16235598/45817531-72725c80-bcb5-11e8-8a32-961f12b6fde0.png)

**Comment by sjanuary** [comment]
@gustavomassa we build appmetrics binaries with VS 2015 so that could be the issue if different runtime C++ libraries are installed.  If that is the case then you might find installing directly from Git would work for you on your work computer (I.e. `npm install https://github.com/RuntimeTools/appmetrics`) because that would cause the binaries to be built from source, rather than extracting the pre-built ones from the npm package.
